development:
  adapter: mysql2
  encoding: utf8
  database: twitter_db
  pool: 10
  username: root
  password: <%= ENV['PASSWORD'] %>

production:
  adapter: mysql2
  encoding: utf8
  database: twitter_production_db
  pool: 10
  username: root
  password: <%= ENV['PASSWORD'] %>

test:
  adapter: mysql2
  encoding: utf8
  database: twitter_test_db
  pool: 10
  username: root
  password: <%= ENV['PASSWORD'] %>